apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 80
      protocol: TCP
      name: dummy
  selector:
    app: {{ .Values.appName }}
    tier: backend
  type: LoadBalancer
