apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-policy
  namespace: dev
  labels:
    app: myapp-policy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-policy
      tier: backend
  template:
    metadata:
      labels:
        app: myapp-policy
        tier: backend
    spec: # Pod spec
      containers:
        - name: myapp-container
          image: "devozs/myapp:1.0.0"
          # both command and args are basically redundant as there is ENTRYPOINT and CMD in the Dockerfile
          # however its required in order to avoid CrashLoopBackOff since this Java main exit one done...
          command: ["/bin/sh"]
          args: ["-c", "java -jar /usr/app/${APP_NAME_VERSION}.jar $NAME & while true; do sleep 3600; done"]
          ports:
            - containerPort: 80
          env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  key: user
                  name: user-configmap-policy
          resources:
            requests:
              memory: "4Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
