apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../apps/base

configMapGenerator:
  - name: myapp-values
    namespace: dev
    files:
      - values.yaml=../../../myapp-chart/values-dev.yaml
